### ISSUE TITLE
Add hardware tutorial / recomendation

### ISSUE THREAD

**Issue by cweinhofer** [balassy/MMM-RemoteTemperature#4]
The second issue is whether you would be interested in adding a hardware tutorial / recomendation to the read me documentation. This is something I could write, but I don't want to create something without knowing if you are interesting in adding it. I found some cheap, plug-and-play Arduino-based hardware that makes an ideal solution for the remote sensor unit, especially for someone just starting out. It would of course be just one option, but it could be helpful for people who are interested in this module but have no idea what an HTTP POST request is let alone how to generate one (like me a few months ago). Let me know if you're interested and I can post more details.

**Comment by balassy** [comment]
I started to work on a hardware+software solution based on ESP8266 in my [wireless-thermometer](https://github.com/balassy/wireless-thermometer) repository. It is currently a work in progress, and I am actively working on it.

I designed this MagicMirror module very universal, so it can work with a good variety of hardware, and I would like to help the users with the hardware side as well. I'm very interested in your tutorial, and I think it would be more convenient if you would create it in your own repository, and I am happy to add a direkt link to it into this module's README.

What do you think?

**Comment by cweinhofer** [comment]
Your [wireless-thermometer ](https://github.com/balassy/wireless-thermometer) code is both great and terrible -- terrible because I now have a bunch more great code to become familiar with and consider adding to my own sketch.

I think your suggestion about keeping the sensor sketches and hardware suggestions in separate locations is a good one -- especially after seeing what you've written. Having links to multiple examples from multiple people will give more options and encourage people to understand the code better.

I'll try to get my code up on a public repository soon (I'll be traveling for a few weeks). Do you have any preferences / suggestions for the hardware part? Maybe something like Instructables or the Arduino Project Hub?

**Comment by balassy** [comment]
No, I do not have any preference, and I do not want to restrict the possibilities in any ways. Any device that can send a HTTP POST request is compatible with this module.

**Comment by cweinhofer** [comment]
Sorry, I should have been more clear. I meant do you have any preferences / suggestions for where to post tutorials for the hardware (i.e. are any sites easier / harder, better / worse when linking from the module's README)?

**Comment by balassy** [comment]
Actually I do not have much experience with other sites, so I do not know how easy it is to post to Instructables or Arduino Project Hub. For myself I prefer Github, because it clearly shows when the project was last updated, and anyone can submit corrections or create a derivative of it.
