### ISSUE TITLE
cURL example

### ISSUE THREAD

**Issue by egomes951** [balassy/MMM-RemoteTemperature#7]
Hi, 

I've an Arduino project where a collect temperature and humidity of each room. 
I'd like to post all rooms temp and hum from my central Aurduino.
Can you please give a cURL example?

Thanks,
Elisio

**Comment by egomes951** [comment]
Ok.... after struggling with this a few days... where goes the solution: curl -X POST http://192.168.1.113:8080/remote-temperature -H 'content-type: application/json' -d '{"temp":"12", "humidity":"1", "sensorId": "1" }'

**Comment by balassy** [comment]
I'm glad it finally solved and thanks for sharing the solution!
