### ISSUE TITLE
cd to module directory

### ISSUE THREAD

**Issue by cweinhofer** [balassy/MMM-RemoteTemperature#8]
Was helping a friend with an MM install and noticed a possible issue in the README. I thought I would check before creating the pull request.

Should there be a `cd ./MMM-RemoteTemperature/` between `git clone https://github.com/balassy/MMM-RemoteTemperature.git` and `npm install` in the **Using the module** section?

**Comment by balassy** [comment]
Hello @cweinhofer,

Yes, you're right, the `cd` command is missing. Would you be so kind to submit a pull request?

Thank you.

**Comment by balassy** [comment]
Fixed with PR #9.
Thank you!
